#!/bin/bash

clear
sleep 1
figlet trojans
echo
sleep 1
echo -e "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo -e " AUTHOR : MR SUKA TAI"
echo -e " TEAM : DARK CLUB LINK (https://chat.whatsapp.com/GfDPRMb91AD8UXpD2jbJVD)"
echo -e "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo -e "1).SEND MALWARE
echo -e "2).SEND Tai ayam ( trojans )"
echo
read -p "pilih>> " virus ( kek tai )
if [[ $virus == "1" ]]
then
read -p "masukkan nomor target ( kek tai )=> " nomor
while [[ true ]]; do
echo "SEND MALWARE ke $nomor telah berhasil"
done
fi
if [[ $virus == "2" ]]
then
read -p "masukkan nomor target ( kek tai )=> " nomor2
while [[ true ]]; do
echo "SEND MALWARE ke $nomor2 telah berhasil"
done
fi
